# -*- coding: utf-8 -*-
db.define_table('edits',Field('page_title', 'string',required=False),
                     Field('is_anon', 'string',required=False),
                     Field('lang', 'string',required=False),
                     Field('url', 'string',required=False),
                     Field('is_unpatrolled', 'string',required=False),
                     Field('parent_rev_id', 'string',required=False),
                     Field('is_bot', 'string',required=False),
                     Field('is_new', 'string',required=False),
                     Field('is_minor', 'string',required=False),
                     Field('summary', 'string',required=False),
                     Field('flags', 'string',required=False),
                     Field('user_name', 'string',required=False),
                     Field('actions', 'string',required=False),
                     Field('ns', 'string',required=False),
                     Field('change_size', 'string',required=False),
                     Field('rev_id', 'string',required=False),
                     Field('epm', 'double',required=False),
                     Field('teds', 'double',required=False),
                     Field('updated', 'datetime' , default=request.now, update=request.now,));

db.define_table('news',Field('page_title', 'string',required=False),
                     Field('en_title', 'string',required=False),
                     Field('lang', 'string',required=False),
                     Field('url', 'string',required=False),
                     Field('weight', 'string',required=False),
                     Field('edit_dist', 'string',required=False),
                     Field('partial_dist', 'string',required=False),
                     Field('ratio', 'string',required=False));
